<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends EntityRepository
{
    public function findLastFifteen()
    {
        $qb = $this->createQueryBuilder('purchase')
            ->orderBy('purchase.id', 'DESC')
            ->setMaxResults(15)
        ;

        return $qb->getQuery()->execute();
    }

    public function findByDate($form){

        $cash = $form->get('cash')->getData();
        $person = $form->get('person')->getData();

        $qb = $this->createQueryBuilder('purchase');

        $qb
            ->where($qb->expr()->between('purchase.createdAt', ':initDate', ':endDate'))
            ->setParameter('initDate', $form->get('initDate')->getData())
            ->setParameter('endDate', $form->get('endDate')->getData());

        if ($cash != 1) {
            $qb
                ->andWhere($qb->expr()->eq('purchase.cash', ':cash'))
                ->setParameter('cash', $cash == 2);
        }
        if ($person !== null) {
            $qb->andWhere($qb->expr()->eq('purchase.person', ':person'))
                ->setParameter('person', $person);
        }

        return $qb->getQuery()->execute();



    }

}
